Setup and Mobile Version Skeleton
iammouaz/Portfolio pull request #1
Opened 2021-08-12 16:47 UTC by iammouaz

Hello,

Kindly review my code for the first Portfolio

thanks a lot

2021-08-12 19:22 UTC, emmanuellekamwa requested changes
**STATUS: CHANGES REQUESTED 🛑🛠**
Hello @iammouaz 👋🏽
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] Please your pull request is not descriptive enough. Try and add the changes that you have made to your project

_Check the comments under the review._👇🏽👀

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-12 19:22 UTC, emmanuellekamwa commented on index.html
> +    <h3 class="can-do">I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded, don’t hestiate to c
- [ ] This text should be wrapped inside a `p` tag and not an `h3` tag. Please fix that.

2021-08-12 19:22 UTC, emmanuellekamwa commented on index.html
> +<img class="social-items" src="/img/micro.png" alt="">
- [ ] The list of icons uses a ul tag to group them, and li per icon; each icon has a link (a tag). Please fix that.

2021-08-12 20:27 UTC, iammouaz commented on README.md
> -
hello but I think I've already modify it in this brunch are you sure ??

2021-08-12 20:28 UTC, iammouaz commented on README.md
> -
hello but I think I've already modify it in this brunch are you sure ??

2021-08-13 03:14 UTC, carlos-ssh requested changes
Hi @iammouaz , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 03:14 UTC, carlos-ssh commented on README.md
>  ## Authors
Kindly provide information related to your project. keep the professionalism simple things make the difference.

2021-08-13 03:14 UTC, carlos-ssh commented on css/style.css
> +
- Kindly add to buttons is `` <a> `` link a or button tag, and follow the button styling: Active, Hover and Pressed.

2021-08-13 09:45 UTC, mke2111 approved these changes
### Hi @iammouaz, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 14:21 UTC, merged